### ISSUE TITLE
Responsive Slider

### ISSUE THREAD

**Issue by ineswillenbrock** [Hauer-Heinrich/hh_slider#4]
TYPO3: 9.5.13, hh_slider: 0.1.6, Firefox 68.4.1 on Android 10 (and Firefox 71.0 on Linux, and some older Safaris of undetermined versions)
The slider stacks the images and the browser does not choose, which image would be the appropriate one as seen in the screenshot.

I "fixed" the issue with setting the max-width of the img to 100% and the height to 100%.

regards - Ines

Should I play around for a real fix?

![Screenshot_20200115-184103](https://user-images.githubusercontent.com/44277221/72460429-11856680-37cd-11ea-9e45-d643ebaab73a.png)

**Comment by Teisi** [comment]
Hello and thank you,
sry i can't reproduce this:
TYPO3: 9.5.13,
hh_slider: 0.1.6, 
Firefox 68.4.1 on Android 9 & 8
Safari 13.0.4 on older and newer mac's

Can you share your slider settings pls?

**Comment by ineswillenbrock** [comment]
sure, in the content element:
`[tx_hhslider_autoplay] = 1`
`[tx_hhslider_autoplay_speed] = 5000`
`[tx_hhslider_animation] = carousel`
`[tx_hhslider_animation_direction] = horizontal`
`[tx_hhslider_animation_speed] = 3000`
`[tx_hhslider_loop] = 1`
`[tx_hhslider_slides_per_view] = 1`
`[tx_hhslider_disable_on_interaction] = 0`
`[tx_hhslider_centered_slides] = 1`
`[tx_hhslider_arrows] = 0`
`[tx_hhslider_pagination] = 1`
`[tx_hhslider_thumbnails] = 0`

perhaps this one is relevant:
`styles.content.imgtext.maxW = 800`

`styles.content.textmedia.maxW = 900`
`styles.content.textmedia.maxWInText = 900`

I included the TS-Template from the extension but I believe I did not configure anything else regarding the slider

**Comment by iocron** [comment]
I would say the only non-breaking fix I see right now would be something like this: 
```
.tns-item picture > img {
	max-width: 100%;
	height: auto;
}
```

**Comment by Teisi** [comment]
Thank you, the question is whether you really want to crop the pictures on your smartphone - which is the case if you don't give the picture a "max-width: 100%; height: auto;". (CSS for Responsive Images).
https://www.w3schools.com/howto/howto_css_image_responsive.asp

Can you please test the following (instead of your max-with 100$ and height 100%)?

.slider-container.tns-horizontal .slider-slide img {
  max-width: 100%;
  height: auto; }

Thanks a lot!

If it fits for you we will include it in the new version, shouldn't be breaking for anyone.

**Comment by ineswillenbrock** [comment]
Works for me - looks the same as my max-width: 100%; height: 100% actually but seems to be more precise.
Thanks!
